# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 255)
        Dialog.setMinimumSize(QtCore.QSize(300, 255))
        Dialog.setMaximumSize(QtCore.QSize(300, 255))
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.solutionsLabel = QtWidgets.QLabel(Dialog)
        self.solutionsLabel.setObjectName("solutionsLabel")
        self.gridLayout_2.addWidget(self.solutionsLabel, 0, 0, 1, 1)
        self.checkWL1 = QtWidgets.QCheckBox(Dialog)
        self.checkWL1.setObjectName("checkWL1")
        self.gridLayout_2.addWidget(self.checkWL1, 1, 0, 1, 1)
        self.checkWL2 = QtWidgets.QCheckBox(Dialog)
        self.checkWL2.setObjectName("checkWL2")
        self.gridLayout_2.addWidget(self.checkWL2, 2, 0, 1, 1)
        self.checkWL3 = QtWidgets.QCheckBox(Dialog)
        self.checkWL3.setObjectName("checkWL3")
        self.gridLayout_2.addWidget(self.checkWL3, 3, 0, 1, 1)
        self.checkEmpty = QtWidgets.QCheckBox(Dialog)
        self.checkEmpty.setObjectName("checkEmpty")
        self.gridLayout_2.addWidget(self.checkEmpty, 4, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.pushCalibrate = QtWidgets.QPushButton(Dialog)
        self.pushCalibrate.setObjectName("pushCalibrate")
        self.gridLayout.addWidget(self.pushCalibrate, 0, 1, 1, 1)
        self.pushCancel = QtWidgets.QPushButton(Dialog)
        self.pushCancel.setObjectName("pushCancel")
        self.gridLayout.addWidget(self.pushCancel, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.solutionsLabel.setText(_translate("Dialog", "Solutions to Calibrate"))
        self.checkWL1.setText(_translate("Dialog", "460 nm"))
        self.checkWL2.setText(_translate("Dialog", "570 nm"))
        self.checkWL3.setText(_translate("Dialog", "710 nm"))
        self.checkEmpty.setText(_translate("Dialog", "Empty"))
        self.pushCalibrate.setText(_translate("Dialog", "Calibrate"))
        self.pushCancel.setText(_translate("Dialog", "Cancel"))
